targets:
  $default:
    builders:
      reflectable:
        generate_for:
          - dash_agent/lib/configuration/command.dart
        options:
          formatted: true # Optional, for better code formatting
