name: dash_agent
description: "Framework package to create and publish dash agents for commanddash"
version: 0.2.1
homepage: https://www.commanddash.io

repository: https://github.com/CommandDash/packages/tree/main/dash_agent
issue_tracker: https://github.com/CommandDash/packages/issues

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  path: ^1.8.3
  meta: ^1.8.0
  http: ^1.0.0
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
