name: dash
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.2.5

executables:
  dash_cli:
    
# Add regular dependencies here.
dependencies:
  ansi_escapes: ^1.1.0
  args: ^2.4.2
  dio: ^5.4.1
  http: ^1.2.1
  interact: ^2.2.0
  oauth2: ^2.0.2
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  