name: dash_cli
description: "CLI tool for building dash agents for CommandDash"
version: 0.2.1
homepage: https://www.commanddash.io

repository: https://github.com/CommandDash/packages/tree/main/dash_cli
issue_tracker: https://github.com/CommandDash/packages/issues

environment:
  sdk: '>=2.19.0 <4.0.0'

executables:
  dash_cli:
    
dependencies:
  ansi_escapes: ^1.1.0
  args: ^2.4.2
  dart_jsonwebtoken: ^2.13.0
  http: ^0.13.6
  image: ^4.2.0
  interact: ^2.2.0
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  