name: commanddash
description: CLI enhancments to Dash-AI
version: 0.0.1
repository: https://github.com/Welltested-AI/commanddash

environment:
  sdk: '>=2.14.0 <4.0.0'

executables:
  commanddash:

# Add regular dependencies here.
dependencies:
  analyzer: ^6.0.0
  args: ^2.4.2
  async: ^2.11.0
  cli_util: ^0.4.1
  rxdart: ^0.27.7
  yaml: ^3.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
