name: Build, Test and Verify Executables

on:
  push:
    branches:
      - build/executables
##TODO: In future, when m1 runners are publicly supported, compiled and verify seperately for arm architectures.
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: commanddash-linux
          - os: macOS-latest
            output-name: commanddash-mac
          - os: windows-latest
            output-name: commanddash-windows.exe
    
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Dart pub get
        run: |
          cd commanddash
          mkdir -p build
          dart pub get
      - name: Compile
        run: |
          cd commanddash
          dart compile exe bin/commanddash.dart -o build/${{ matrix.output-name }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output-name }}  # Dynamically name the artifact based on the OS
          path: commanddash/build/${{ matrix.output-name }}
  
  test:
    needs: build
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary-name: commanddash-linux
          - os: windows-latest
            binary-name: commanddash-windows.exe
          - os: macos-latest
            binary-name: commanddash-mac
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.binary-name }}
          path: ./executable
      
      # Ensure binary is executable (necessary for Unix-based systems)
      - name: Make binary executable
        if: matrix.os != 'windows-latest'
        run: chmod +x ./executable/${{ matrix.binary-name }}
      
      # Execute a basic command or test. In this example "--version" is used,
      # you should adjust it to fit a simple validation command for your executable.
      - name: Test binary
        run: ./executable/${{ matrix.binary-name }} --version